FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g serverless

COPY backend/requirements.txt ./backend/requirements.txt
RUN pip install -r backend/requirements.txt -t backend/dep/

CMD ["serverless", "deploy"]